// Chuỗi giao diện English
#include "lang.h"

#include "gfx.h"

const char *const lang_strings_en[S_COUNT] = {
    [S_APP_SUBTITLE]   = "J2ME emulator for Nintendo Switch",
    [S_GAME_COUNT]     = "%d apps",
    [S_FOLDER]         = "Folder: %s",
    [S_NO_MIDLET]      = "No MIDlet-1 in MANIFEST: may not run",
    [S_MENU_HINTS]     = ICON_A " Open   " ICON_MINUS " Options   " ICON_X " Settings   " ICON_Y " Rescan   " ICON_R " Upload   " ICON_L " Delete   " ICON_PLUS " Exit",

    [S_PICK_MIDLET]    = "Choose MIDlet:  " ICON_A " Run   " ICON_B " Back",

    [S_EMPTY_TITLE]    = "No apps yet",
    [S_EMPTY_COPY]     = "Copy your .jar apps (and the matching .jad if any) to:",
    [S_EMPTY_SUBDIR]   = "Subfolders are supported, e.g. games/RPG/game.jar",
    [S_EMPTY_VIDEO]    = "Video files (.mp4, .3gp...) placed there can be played too",
    [S_EMPTY_RESCAN]   = "Then press " ICON_Y " to rescan",

    [S_ERROR_FMT]      = "Error: %s",
    [S_RESCANNED]      = "Rescanned: %d files",
    [S_SETTINGS_SAVED] = "Settings saved",
    [S_GAME_EXITED]    = "App closed",

    [S_ERR_SYSLIB]     = "System library is corrupted",
    [S_ERR_OPEN_JAR]   = "Cannot open the JAR file",
    [S_ERR_NO_MIDLET]  = "JAR has no MIDlet-1 in MANIFEST",
    [S_ERR_VM]         = "VM startup error: %s",
    [S_ERR_MIDLET]     = "Cannot start MIDlet: %s",
    [S_GAME_ENDED]     = "App ended (no threads left)",
    [S_GAME_CRASHED]   = "App crashed, saved crash/%s",
    [S_APP_CRASHED_BEFORE] = "The app crashed last time, saved crash/%s",

    [S_EXIT_CONFIRM]   = "Press - (or Esc) again to exit the app",
    [S_SCREEN_INFO_FPS] = "%dx%d  -  %d FPS limit",
    [S_HELP_DPAD]      = "Directions",
    [S_HELP_SOFT_RIGHT] = "Right soft key",
    [S_HELP_SOFT_LEFT] = "Left soft key",
    [S_HELP_EXIT]      = "Exit app",

    [S_SETTINGS]       = "Settings",
    [S_GAME_OPTIONS]   = "App options",
    [S_FPS_LIMIT]      = "FPS limit",
    [S_FPS_HINT]       = "Maximum frames per second of the app. Keeps apps at the right speed and saves battery.",
    [S_UNLIMITED]      = "Unlimited",
    [S_DEFAULT_FMT]    = "Default (%s)",
    [S_SCREEN_SIZE]    = "Screen size",
    [S_SCREEN_SIZE_DEFAULT] = "Default screen size",
    [S_SCREEN_SIZE_HINT_GAME] = "Auto: taken from the app's MANIFEST, otherwise the default size. "
                                "Choose 'Custom' to enter any size.",
    [S_SCREEN_SIZE_HINT] = "Used for apps that do not declare a size. The most common is 240x320. "
                           "Choose 'Custom' to enter any size.",
    [S_AUTO]           = "Auto",
    [S_CUSTOM]         = "Custom",
    [S_ORIENTATION]    = "Orientation",
    [S_ORIENT_HINT]    = "Portrait: taller than wide (common phones). Landscape: wider than tall (e.g. 320x240).",
    [S_PORTRAIT]       = "Portrait",
    [S_LANDSCAPE]      = "Landscape",
    [S_SQUARE]         = "Square",
    [S_WIDTH]          = "Width",
    [S_HEIGHT]         = "Height",
    [S_SIZE_EDIT_HINT] = "Left/Right: +-1, L/R: +-10, A: type a number. Range 64 - 1280.",
    [S_KB_WIDTH]       = "Screen width",
    [S_KB_HEIGHT]      = "Screen height",
    [S_LANGUAGE]       = "Language / Ngôn ngữ",
    [S_LANGUAGE_HINT]  = "Interface language. Apps also receive the matching microedition.locale.",
    [S_KEYMAP]         = "Key layout",
    [S_KEYMAP_HINT]    = "Soft key / navigation codes of the phone brand the app was made for. "
                         "Use it when soft keys or Fire do not work.",
    [S_KEYBIND]        = "Button mapping",
    [S_KEYBIND_HINT]   = "Choose the phone key each Switch button presses. Press " ICON_A " to open.",
    [S_KEYBIND_HINT_APP] = "Choose the phone key each Switch button presses, for this app only. Buttons left on "
                           "Default follow the global settings. Press " ICON_A " to open.",
    [S_KEYBIND_DEFAULT] = "Default",
    [S_KEYBIND_CHANGED] = "%d buttons changed",
    [S_KEYBIND_INHERIT] = "Same as global",
    [S_KEYBIND_OWN]    = "%d own buttons",
    [S_KEYBIND_GLOBAL] = "Global settings",
    [S_KEYBIND_HINTS]  = ICON_LEFT ICON_RIGHT " Change key   " ICON_Y " Default   " ICON_X " Reset all   "
                         ICON_B " Back",
    [S_KEYBIND_PHONE]  = "Phone keys",
    [S_BTN_LSTICK]     = "Left stick click",
    [S_BTN_RSTICK]     = "Right stick click",
    [S_BTN_RS_UP]      = "Right stick up",
    [S_BTN_RS_DOWN]    = "Right stick down",
    [S_BTN_RS_LEFT]    = "Right stick left",
    [S_BTN_RS_RIGHT]   = "Right stick right",
    [S_KEY_NONE]       = "None",
    [S_KEY_UP]         = "Up",
    [S_KEY_DOWN]       = "Down",
    [S_KEY_LEFT]       = "Left",
    [S_KEY_RIGHT]      = "Right",
    [S_KEY_CLEAR]      = "Clear (C)",
    [S_SCALE_MODE]     = "Scaling",
    [S_SCALE_HINT]     = "The app screen is upscaled by the GPU. Sharp: crisp, even pixels (recommended). "
                         "Pixel: crispest but pixels may be uneven. Integer: exact 2x/3x with borders.",
    [S_SCALE_SMOOTH]   = "Sharp",
    [S_SCALE_SHARP]    = "Pixel",
    [S_SCALE_INTEGER]  = "Pixel (integer)",
    [S_SHOW_HELP]      = "Show key help while running",
    [S_SHOW_HELP_HINT] = "Key map shown left of the app screen.",
    [S_SHOW_FPS]       = "Show FPS",
    [S_SHOW_FPS_HINT]  = "Top left: frames the app draws per second, CPU % spent running the app, Java memory and the emulator's total RAM.",
    [S_FONT_SCALE]     = "Font size",
    [S_FONT_SCALE_HINT] = "Scale in-app text relative to the original size. Useful for Opera Mini, especially with a "
                          "larger screen size (e.g. 480x800 + 200%). Apps lay out text using the new size.",
    [S_SMOOTH_TEXT]    = "Smooth text",
    [S_SMOOTH_TEXT_HINT] = "Anti-aliased in-app text. Recommended for text-heavy apps like Opera Mini; "
                           "when off, text is drawn as pixels like on real phones.",
    [S_CHECK_UPDATE]   = "Check for updates",
    [S_CHECK_UPDATE_HINT] = "Each time the app starts, ask GitHub whether a newer J2ME-NXX exists; if so, offer to "
                            "download it and replace the .nro file. Needs an Internet connection.",
    [S_UPDATE_BADGE]   = "New v%s  " ICON_B " Update",
    [S_UPDATE_TITLE]   = "New version: v%s",
    [S_UPDATE_CURRENT] = "You have v%s",
    [S_UPDATE_PROMPT_HINTS] = ICON_A " Download and update   " ICON_B " Later",
    [S_UPDATE_FAILED]  = "Update failed: %s",
    [S_UPDATE_FAILED_HINTS] = ICON_A " Retry   " ICON_B " Close",
    [S_UPDATE_DOWNLOADING] = "Downloading v%s...",
    [S_UPDATE_CANCELLING] = "Cancelling...",
    [S_UPDATE_ETA]     = "%d:%02d left",
    [S_UPDATE_KEEP_OPEN] = "Do not exit the app or turn off the console while downloading. The old .nro is only "
                           "replaced once the download is complete and verified.",
    [S_UPDATE_CANCEL_HINT] = ICON_B " Cancel",
    [S_UPDATE_DONE]    = "Updated to v%s",
    [S_UPDATE_DONE_INFO] = "The .nro file has been replaced. Restart the app to use the new version.",
    [S_UPDATE_DONE_HINTS] = ICON_A " Restart   " ICON_B " Later",
    [S_UPDATE_DONE_DESKTOP] = "The desktop build only downloads the .nro to the data folder for testing.",
    [S_UPDATE_CLOSE_HINT] = ICON_A " Close",
    [S_VKB_BUBBLE]     = "Virtual keyboard bubble",
    [S_VKB_BUBBLE_HINT] = "Shows a small bubble on the touch screen while running (drag to move). Tap it to open a "
                          "floating QWERTY keyboard with a number row for typing in apps; × collapses it back.",
    [S_VPAD]           = "On-screen keypad",
    [S_VPAD_HINT]      = "Phone keypad on the touch screen while running: joystick (follows the left stick), soft keys, "
                         "Fire, number keys. Turn it on or off per app in App options.",
    [S_VPAD_HINT_APP]  = "Phone keypad on the touch screen while this app runs. The layout is set in the global settings.",
    [S_VPAD_LAYOUT]    = "On-screen keypad layout",
    [S_VPAD_LAYOUT_HINT] = "Keys are placed on the Switch screen, shared by all apps. Drag each key to move it, drag the corner dot to resize; set rounded corners, opacity and hide "
                           "keys you don't need. Keys placed next to each other snap together. Press " ICON_A " to open.",
    [S_VPAD_CUSTOMIZED] = "%s, customized",
    [S_VPAD_STICK]     = "Joystick",
    [S_VPAD_KEY_FMT]   = "Key %s",
    [S_VPAD_PICK]      = "Tap a key to edit it",
    [S_VPAD_HIDE]      = "Hide",
    [S_VPAD_SHOW]      = "Show",
    [S_VPAD_RADIUS]    = "Corner %d",
    [S_VPAD_OPACITY]   = "Opacity %d%%",
    [S_VPAD_SNAP]      = "Snap: %s",
    [S_VPAD_RESET]     = "Default",
    [S_VPAD_RESET_CONFIRM] = "Tap Default again to reset the whole layout",
    [S_VPAD_DONE]      = "Done",
    [S_VPAD_EDIT_HELP] = "Drag a key to move it, drag the corner dot to resize. Controller: " ICON_L "/" ICON_R
                         " pick key, D-pad move, " ICON_X "/" ICON_Y " bigger / smaller, " ICON_A " hide / show, " ICON_B
                         " done.",
    [S_SOUNDFONT]      = "MIDI SoundFont",
    [S_SOUNDFONT_HINT] = "Play MIDI music with a SoundFont for real-instrument sound: TimGM6mb is built in, or copy a .sf2 "
                         "file to sdmc:/switch/j2me-nxx/soundfonts/. Off: wave synth, lighter.",
    [S_SOUNDFONT_AUTO] = "Auto (%s)",
    [S_SOUNDFONT_NONE] = "Off - wave synth",
    [S_SOUNDFONT_BUILTIN] = "TimGM6mb (built-in)",
    [S_SYSTEM_FONT]    = "System font",
    [S_SYSTEM_FONT_HINT] = "In-app text uses the device font (Switch: system fonts with Japanese, Chinese, Korean), "
                           "always smooth and drawn sharp at screen resolution. When off, the app font is used; "
                           "characters missing from either font are taken from the other.",
    [S_ON]             = "On",
    [S_OFF]            = "Off",
    [S_SETTINGS_HINTS] = ICON_LEFT ICON_RIGHT " Change   " ICON_A " Select / enter number   " ICON_B " Save and back",
    [S_VIDEO_TAG]      = "Video",
    [S_VIDEO_HINTS]    = ICON_A " Play / pause   " ICON_LEFT ICON_RIGHT " Seek 10 s   " ICON_L "/" ICON_R " Seek 1 min   " ICON_UP ICON_DOWN " Volume   " ICON_B " Exit",
    [S_VIDEO_PAUSED]   = "Paused",
    [S_VIDEO_ENDED]    = "Ended",
    [S_VOLUME_FMT]     = "Volume %d%%",
    [S_ERR_VIDEO]      = "Cannot open video",
    [S_ERR_NO_VIDEO_BUILD] = "This build has no FFmpeg: video is not supported",
    [S_VIDEO_NO_OPTIONS] = "Videos have no options",
    [S_LINK_OPENING]   = "Opening link...   " ICON_B " Cancel",
    [S_LINK_FAILED]    = "Cannot open link",
    [S_BROWSER_NEEDS_APP] = "To open the browser, run hbmenu in full RAM mode (hold R while launching a game)",
    [S_EMPTY_UPLOAD]   = "Or press " ICON_R " to send apps and videos from your phone with a QR code",
    [S_UPLOAD_TITLE]   = "Send apps and videos from your phone",
    [S_UPLOAD_STEP1]   = "1. Connect your phone to the same Wi-Fi as the Switch",
    [S_UPLOAD_STEP2]   = "2. Scan the QR code with the camera (or open the address below)",
    [S_UPLOAD_STEP3]   = "3. Choose .jar apps (and .jad if any) or videos to send",
    [S_UPLOAD_WAITING] = "Waiting for your phone...",
    [S_UPLOAD_RECEIVING] = "Receiving %s",
    [S_UPLOAD_RECEIVED] = "Received %d file(s), latest: %s",
    [S_UPLOAD_NO_NET]  = "The Switch is not connected to a network. Connect to Wi-Fi and try again.",
    [S_UPLOAD_SERVER_FAILED] = "Cannot open a network port: %s",
    [S_UPLOAD_WRITE_FAILED] = "Cannot write the file to the SD card",
    [S_UPLOAD_HINTS]   = ICON_B " Close",
    [S_UPLOAD_DONE_STATUS] = "Received %d file(s) from your phone",
    [S_DELETE_GAME]    = "Delete this app?",
    [S_DELETE_VIDEO]   = "Delete this video?",
    [S_DELETE_KEEP_SAVE] = "Save data and per-app options are kept.",
    [S_DELETE_HINTS]   = ICON_A " Delete   " ICON_B " Cancel",
    [S_DELETED]        = "Deleted: %s",
    [S_DELETE_FAILED]  = "Could not delete: %s",
    [S_WEB_TITLE]      = "Send apps and videos to the Switch",
    [S_WEB_INTRO]      = "Choose .jar apps (and .jad if any) or videos (.mp4, .3gp, .mkv...). Files are saved to the "
                         "games folder and show up in the list once you close the send screen on the Switch.",
    [S_WEB_CHOOSE]     = "Choose apps / videos",
    [S_WEB_WAITING]    = "Waiting",
    [S_WEB_SENDING]    = "Sending",
    [S_WEB_DONE]       = "Sent",
    [S_WEB_FAILED]     = "Failed",
    [S_WEB_NETWORK]    = "lost connection to the Switch",
    [S_WEB_WRONG_TYPE] = "Only .jar / .jad apps or videos are accepted",
    [S_WEB_ALL_DONE]   = "Done! Close the send screen on the Switch to see the new files in the list.",
};
